[versions]
activity-ktx = "1.8.0"
android-gradle-plugin = "8.1.2"
appcompat = "1.6.1"
biometric = "1.1.0"
core-ktx = "1.12.0"
jgit = "6.5.0.202303070854-r"
espresso-core = "3.5.1"
fragment-ktx = "1.6.1"
jsr305 = "3.0.2"
junit = "1.1.5"
kotlin = "1.9.10"
material = "1.10.0"
preference-ktx = "1.2.1"
security-crypto = "1.1.0-alpha06"

[libraries]
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security-crypto" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
