[versions]
activity-ktx = "1.9.3"
android-gradle-plugin = "8.7.3"
appcompat = "1.7.0"
biometric = "1.1.0"
core-ktx = "1.15.0"
jgit = "7.1.0.202411261347-r"
espresso-core = "3.6.1"
fragment-ktx = "1.8.5"
junit = "1.2.1"
kotlin = "2.1.0"
material = "1.12.0"
preference-ktx = "1.2.1"
security-crypto = "1.1.0-alpha06"
spotbugs = "4.8.6"

[libraries]
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security-crypto" }
spotbugs = { group = "com.github.spotbugs", name = "spotbugs-annotations", version.ref = "spotbugs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
